config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  devise_for :users

  root             to: 'tweets#index'
  get '/obs',      to:  'tweets#obs'
  get '/reader',   to:  'tweets#reader'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:hashtag, :automode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.slim
doctype html
html lang="en" 
  head
    /! Required meta tags
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" /
    /! Metro 4
    link href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css" rel="stylesheet" /
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
body
  == yield

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Nightjar</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/layouts/test.html.slim
doctype html
html
  head
    title
      | Nightjar
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/tweets/_form.html.slim
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      ul
        - @tweet.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :hashtag
    = f.text_field :hashtag
  .field
    = f.label :automode
    = f.check_box :automode
  .actions = f.submit

app/views/tweets/edit.html.slim
h1 Editing tweet

== render 'form'

=> link_to 'Show', @tweet
'|
=< link_to 'Back', tweets_path

app/views/tweets/index.html.slim
h1 Listing tweets

table
  thead
    tr
      th Hashtag
      th Automode
      th
      th
      th

  tbody
    - @tweets.each do |tweet|
      tr
        td = tweet.hashtag
        td = tweet.automode
        td = link_to 'Show', tweet
        td = link_to 'Edit', edit_tweet_path(tweet)
        td = link_to 'Destroy', tweet, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.slim
h1 New tweet

== render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.slim
p#notice = notice

p
  strong Hashtag:
  = @tweet.hashtag
p
  strong Automode:
  = @tweet.automode

=> link_to 'Edit', edit_tweet_path(@tweet)
'|
=< link_to 'Back', tweets_path